### ISSUE TITLE
Native module could not be located

### ISSUE THREAD

**Issue by kegesch** [evonox/electron-native-plugin#1]
Hey there, thanks for this plugin. I currently have a great struggle to use native node modules in my electron app. 
So i started a new project an wanted setup a boilerplate. 
I tried to use your plugin and used a example native node module to test it. 
Unfortunately after rebuilding the module it will be copied to my specified build folder, but it is renamed wrongly. To be more pecise: I am using the module "node-mac-notifier" which expects ```Notification.node``` at the build folder (besides the bundle). But your plugin generates a ```node-mac-notifier.node``` file. And therefore electron produces this error: 
```
Uncaught Error: Could not locate the bindings file. Tried:
 → /Users/.../build/Notification.node
 → /Users/.../build/Debug/Notification.node
 → /Users/.../build/Release/Notification.node
 → /Users/.../out/Debug/Notification.node
 → /Users/.../Debug/Notification.node
 → /Users/.../out/Release/Notification.node
 → /Users/.../Release/Notification.node
 → /Users/.../build/default/Notification.node
 → /Users/.../compiled/10.2.0/darwin/x64/Notification.node
    at bindings (bindings.js:93)
    at Object../node_modules/node-mac-notifier/index.js (index.js:5)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Module../src/index.tsx (index.tsx:1)
    at __webpack_require__ (bootstrap:724)
    at fn (bootstrap:101)
    at Object.0 (index.tsx:14)
    at __webpack_require__ (bootstrap:724)
    at ./node_modules/ansi-html/index.js.module.exports (bootstrap:791)
```

You can look at my webpack.conf at https://github.com/Y0nnyy/electron-react-boilerplate/tree/native-module.
Am i missing something?

**Comment by evonox** [comment]
Hi @Y0nnyy ,
I cannot find your **binding.gyp** file. It might help to set the property **"target_name"** in it. 
You may find some samples with my project [here](https://github.com/evonox/electron-native-plugin-samples).
As well as the docs for **binding.gyp** may be found [here](https://github.com/nodejs/node-gyp).
As I have studied the source, ElectronNativePlugin should use the filename that is produced by ElectronRebuild process.
Otherwise if you like ElectronNativePlugin, feel free to fork it and use as you like. To be honest,  I do not have much time to continue its developement. It is still a bit work-in-progress.
Please let me know if my advice helped.

**Comment by kegesch** [comment]
Thanks for your reply @evonox. If understood correctly the ```binding.gyp``` file must be represent in the native nodule module and defines which resources the project contains and what *node-gyp* should compile.

I am building a boilerplate, therefore i don't know why a ```binding.gyp``` should be there.

**Comment by evonox** [comment]
Hi @Y0nnyy ,
thanks very much for the pull request. I have sent you the invitation to 4 repositories of Electron Native plugin and I will give you the full write access if you wish. First I wanted to transfer the ownership of these projects to you, as I see you have a big interest in this project, but I cannot do that till exists the fork you have made from Electron Native Plugin. Let me know if you would like to take over this set of projects. I would feel very happy if someone will continue with it.
